### ISSUE TITLE
Get rid of setuptools as a runtime dependency

### ISSUE THREAD

**Issue by flying-sheep** [ronaldoussoren/altgraph#21]
`pkg_resources` is provided by setuptools:

https://github.com/ronaldoussoren/altgraph/blob/e288b5332310deac0ef356294a6bf836cfcd0717/altgraph/__init__.py#L144

The stdlib’s replacement for this line would be

```py
from importlib.metadata import version

 __version__ = version("altgraph")
```

If you want to be compatible with Python <3.8, you could do:

```py
try:
    from importlib.metadata import version
except ImportError:  # Python <3.8
    from importlib_metadata import version

 __version__ = version("altgraph")
```

which would use this conditional dependency: `importlib-metadata; python_version < '3.8'`

You could also just do #12 instead. Flit sources the metadata version from a version string in `__init__.py` so this would just become `__version__ = '0.17.4'`

**Comment by tobylightheart** [comment]
This usage of `pkg_resources` is breaking for me in Windows. I haven't done exhaustive testing, but L144 in `__init__.py` was throwing "distribution was not found" errors in a clean venv in Python 3.11.8 (Windows). 

Using the `importlib` approach resolved the error.

```
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import altgraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Toby\_code\venv\altgraph\Lib\site-packages\altgraph\__init__.py", line 144, in <module>
    __version__ = pkg_resources.require("altgraph")[0].version
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toby\_code\venv\altgraph\Lib\site-packages\pkg_resources\__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Toby\_code\venv\altgraph\Lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'altgraph' distribution was not found and is required by the application
```

**Comment by Avasam** [comment]
`pkg_resources` is getting removed from `setuptools` and has a current deadline of December this year.
- https://github.com/pypa/setuptools/issues/3085
- https://github.com/pypa/setuptools/pull/5007
- https://github.com/pypa/setuptools/commit/9c28cdffd423f83e43dbfd39fc793c251da48585
